/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('antdv-next')['Alert']
    AApp: typeof import('antdv-next')['App']
    AButton: typeof import('antdv-next')['Button']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    ACol: typeof import('antdv-next')['Col']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADirectoryTree: typeof import('antdv-next')['DirectoryTree']
    AFlex: typeof import('antdv-next')['Flex']
    AImage: typeof import('antdv-next')['Image']
    AResult: typeof import('antdv-next')['Result']
    ARow: typeof import('antdv-next')['Row']
    ATable: typeof import('antdv-next')['Table']
    ATabs: typeof import('antdv-next')['Tabs']
    ATypographyText: typeof import('antdv-next')['TypographyText']
    ChartCard: typeof import('./../src/components/ChartCard/index.tsx')['default']
    IconPicker: typeof import('./../src/components/IconPicker/index.tsx')['default']
    IconView: typeof import('./../src/components/IconView/index.tsx')['default']
    Notice: typeof import('./../src/components/Notice/index.tsx')['default']
    NumberInfo: typeof import('./../src/components/NumberInfo/index.jsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLang: typeof import('./../src/components/SelectLang/index.tsx')['default']
    Trend: typeof import('./../src/components/Trend/index.tsx')['default']
  }
}

// For TSX support
declare global {
  const AAlert: typeof import('antdv-next')['Alert']
  const AApp: typeof import('antdv-next')['App']
  const AButton: typeof import('antdv-next')['Button']
  const ACheckbox: typeof import('antdv-next')['Checkbox']
  const ACol: typeof import('antdv-next')['Col']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const ADirectoryTree: typeof import('antdv-next')['DirectoryTree']
  const AFlex: typeof import('antdv-next')['Flex']
  const AImage: typeof import('antdv-next')['Image']
  const AResult: typeof import('antdv-next')['Result']
  const ARow: typeof import('antdv-next')['Row']
  const ATable: typeof import('antdv-next')['Table']
  const ATabs: typeof import('antdv-next')['Tabs']
  const ATypographyText: typeof import('antdv-next')['TypographyText']
  const ChartCard: typeof import('./../src/components/ChartCard/index.tsx')['default']
  const IconPicker: typeof import('./../src/components/IconPicker/index.tsx')['default']
  const IconView: typeof import('./../src/components/IconView/index.tsx')['default']
  const Notice: typeof import('./../src/components/Notice/index.tsx')['default']
  const NumberInfo: typeof import('./../src/components/NumberInfo/index.jsx')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SelectLang: typeof import('./../src/components/SelectLang/index.tsx')['default']
  const Trend: typeof import('./../src/components/Trend/index.tsx')['default']
}